services:
  app: 
    build:
      context: .
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    volumes:
      - ./app:/srv
      - ./db:/srv/db
      - ./share:/srv/static/share
    ports:
      - '6789:6789'
      - '8765:8765'
